name: CD E2E

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

on:
  workflow_dispatch:
    inputs: 
      environment:
        type: environment
        description: Target environment for deployment
    
  # push: 
  #   tags:
  #     - 'v*.*.*'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting
        run: echo "${{ github.event.inputs.environmet }}"
