name: Deploy Lambda to Dev

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

on:
  workflow_dispatch:
    
  push: 
    tags:
      - 'v*.*.*'

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: ./app

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          ## the following creates an ARN based on the values entered into github secrets
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: github-actions-lambda-${{ vars.ENV_NAME }}

      - name: Deploy to Lambda
        run: |
          # Zip your Node.js Lambda function code
          zip -r function.zip .

          # Update your Lambda function on AWS
          aws lambda update-function-code \
            --function-name ${{ vars.FUNCTION_NAME }} \
            --zip-file fileb://function.zip

  
